/*
 * Copyright (c) 2026 Gradum team, some rights reserved.
 * For licensing terms and conditions, see the MIT LICENSE file.
 *
 * ErrorCode.kt  2026-06-30 23:35:47 Changed by gwy
 */

package gradum.idea.chat.model

enum class ErrorCode(val code: String) {
  INVALID_PARAMETER("INVALID_PARAMETER"),
  IO_ERROR("IO_ERROR"),
  FILE_NOT_FOUND("FILE_NOT_FOUND"),
  CODE_NOT_FOUND("CODE_NOT_FOUND"),
  MULTIPLE_MATCHES("MULTIPLE_MATCHES"),
  EMPTY_RESULT("EMPTY_RESULT"),
  COMMAND_BLOCKED("COMMAND_BLOCKED"),
  TIMEOUT("TIMEOUT"),
  ALREADY_INITIALIZED("ALREADY_INITIALIZED"),
  NOT_INITIALIZED("NOT_INITIALIZED"),
  ALL_COMPLETED("ALL_COMPLETED"),
  FILE_TOO_LARGE("FILE_TOO_LARGE"),
  CLIENT_ERROR("CLIENT_ERROR"),
  PERMISSION_DENIED("PERMISSION_DENIED"),
  INTERRUPTED("INTERRUPTED"),
  TOOL_NOT_PERMITTED("TOOL_NOT_PERMITTED");
}
