#
# Copyright (c) 2026 Gradum team, some rights reserved.
# For licensing terms and conditions, see the MIT LICENSE file.
#
# gradle.properties  2026-08-14 22:05:52 Changed by gwy
#
org.gradle.jvmargs=-Xmx2048m
org.gradle.java.home=/opt/homebrew/opt/openjdk@25
kotlin.compiler.execution.strategy=in-process
pluginVersion=0.9.0
pluginSinceBuild=251.0
pluginUntilBuild=251.*
