"""IO utilities for logging and context management."""

import json
import logging
import re
import string
import time
from pathlib import Path
from typing import Any, Optional

from utils.format import format_log_entry

_logger = logging.getLogger(__name__)


class LogManager:
    """Manages log operations with real-time writing and deferred buffering."""

    REALTIME_EVENTS = {"tool_call", "thinking", "llm_response", "final_llm_response"}

    def __init__(self, output_dir: Path, enable_realtime: bool = True):
        self._output_dir = output_dir
        self._file_handle: Optional[Any] = None
        self._buffer: list[dict] = []
        self._enable_realtime = enable_realtime

    def init_log(self, user_input: str) -> None:
        """Initialize log file and write metadata."""
        self._output_dir.mkdir(parents=True, exist_ok=True)
        log_file = self._output_dir / "log.txt"

        self._file_handle = open(log_file, "w", encoding="utf-8", newline="\n")

        metadata = {
            "user_input": user_input,
            "start_time": time.strftime("%Y-%m-%d %H:%M:%S"),
            "status": "running",
        }
        self._write_entry({"type": "_metadata", "timestamp": metadata["start_time"], "data": metadata})

    def append(self, event_type: str, data: Any, force_write: bool = False) -> None:
        """Append log entry with optional real-time writing."""
        entry = {
            "type": event_type,
            "timestamp": time.strftime("%Y-%m-%d %H:%M:%S"),
            "data": data,
        }

        if self._enable_realtime and event_type in self.REALTIME_EVENTS:
            self._write_entry(entry)
        else:
            self._buffer.append(entry)
            if force_write:
                for e in self._buffer:
                    self._write_entry(e)
                self._buffer.clear()

    def flush(self) -> None:
        """Flush buffered log entries."""
        for entry in self._buffer:
            self._write_entry(entry)
        self._buffer.clear()

    def close(self) -> None:
        """Close file handle (call at end of session)."""
        if self._file_handle:
            self._file_handle.flush()
            self._file_handle.close()
            self._file_handle = None

    def _write_entry(self, entry: dict) -> None:
        """Write a single log entry to file."""
        if not self._file_handle:
            return

        formatted = format_log_entry(entry)
        if formatted:
            self._file_handle.write(formatted + "\n\n")
            self._file_handle.flush()

    @staticmethod
    def read_log(log_file: Path) -> dict[str, Any]:
        """Read log file and return structured data.

        Parses the human-readable log format generated by format_log_entry.
        Format:
            [type] timestamp
              key: value
              content
        """
        if not log_file.exists():
            return {}

        metadata: dict[str, Any] = {}
        events: list[dict[str, Any]] = []
        completion: dict[str, Any] = {}

        with open(log_file, "r", encoding="utf-8") as f:
            content = f.read()

        # Split by empty lines (entries are separated by double newlines)
        raw_entries = content.split("\n\n")

        for entry in raw_entries:
            entry = entry.strip()
            if not entry:
                continue

            lines = entry.split("\n")
            if not lines:
                continue

            # Parse first line: [type] timestamp
            first_line = lines[0]
            match = re.match(r"\[(\w+)]\s+(.+)", first_line)
            if not match:
                continue

            entry_type = match.group(1)
            timestamp = match.group(2)

            # Parse data from remaining lines
            data: dict[str, Any] = {}
            content_lines = []

            for line in lines[1:]:
                line = line.strip()
                if not line:
                    continue

                # Check for key: value format
                key_value_match = re.match(r"(\w+):\s*(.+)", line)
                if key_value_match:
                    key = key_value_match.group(1)
                    value = key_value_match.group(2)
                    # Try to parse numbers
                    try:
                        data[key] = int(value)
                    except ValueError:
                        try:
                            data[key] = float(value)
                        except ValueError:
                            data[key] = value
                else:
                    content_lines.append(line)

            # Handle content field
            if content_lines:
                data["content"] = "\n".join(content_lines)

            # Categorize by type
            if entry_type == "meta":
                metadata = data
            elif entry_type == "end":
                completion = data
            else:
                events.append({
                    "type": entry_type,
                    "timestamp": timestamp,
                    "data": data
                })

        return {"metadata": metadata, "events": events, "completion": completion}


class ContextManager:
    """Manages conversation context persistence."""

    def __init__(self, output_dir: Path, max_messages: int = 30):
        self._output_dir = output_dir
        self._max_messages = max_messages

    def save(self, messages: list[dict], model: str, full_read_files: Optional[set[str]] = None) -> bool:
        """Save conversation context to JSON file.

        Args:
            messages: List of conversation messages
            model: Model name
            full_read_files: Set of file paths that were fully read (without line_range).
                             These file contents will not be saved since LLM already knows them.
        """
        context_file = self._output_dir / "context.json"
        self._output_dir.mkdir(parents=True, exist_ok=True)

        saveable = [m for m in messages if m.get("role") not in ("system", "tool")]
        cleaned = self._clean_messages(saveable, full_read_files or set())

        context_data = {
            "messages": cleaned,
            "timestamp": time.strftime("%Y-%m-%d %H:%M:%S"),
            "model": model,
            "message_count": len(cleaned),
        }

        try:
            with open(context_file, "w", encoding="utf-8") as f:
                json.dump(context_data, f, ensure_ascii=False, indent=2)
            return True
        except (IOError, OSError, TypeError) as e:
            _logger.error("Failed to save context: %s", e)
            return False

    def load(self) -> list[dict]:
        """Load conversation context from JSON file."""
        context_file = self._output_dir / "context.json"

        if not context_file.exists() or not context_file.is_file():
            return []

        try:
            with open(context_file, "r", encoding="utf-8") as f:
                context_data = json.load(f)

            messages = context_data.get("messages", [])
            if not isinstance(messages, list):
                return []

            filtered = [m for m in messages if m.get("role") not in ("system", "tool")]
            return filtered[-self._max_messages:]

        except (json.JSONDecodeError, IOError, OSError) as e:
            _logger.error("Failed to load context: %s", e)
            return []

    def _clean_messages(self, messages: list[dict], full_read_files: Optional[set[str]] = None) -> list[dict]:
        """Clean messages for storage to reduce size.

        Args:
            messages: List of messages to clean
            full_read_files: File paths that were fully read. Their content will be
                            replaced with a summary since LLM already knows them.
        """
        if full_read_files is None:
            full_read_files = set()

        cleaned = []
        pending_assistant = None

        for msg in messages:
            role = msg.get("role")
            content = msg.get("content", "")

            if role == "assistant":
                if content is None or (isinstance(content, str) and not content.strip()):
                    continue
                pending_assistant = msg
            elif role == "user":
                if pending_assistant:
                    cleaned.append(self._simplify_content(pending_assistant))
                    pending_assistant = None
                cleaned.append(self._simplify_content(msg))
            elif role == "tool":
                simplified = self._maybe_summarize_tool_content(msg, full_read_files)
                if simplified:
                    cleaned.append(simplified)

        if pending_assistant:
            cleaned.append(self._simplify_content(pending_assistant))

        return cleaned

    @staticmethod
    def _maybe_summarize_tool_content(msg: dict, full_read_files: set[str]) -> Optional[dict]:
        """Discard full file read content - LLM already knows it from context.

        Args:
            msg: Tool message
            full_read_files: Set of file paths that were fully read

        Returns:
            None to skip this message (file was fully read), msg to keep it
        """
        content = msg.get("content", "")

        if not content.startswith("Success: Read "):
            return msg

        for file_path in full_read_files:
            if f'Success: Read {file_path}' in content:
                return None
        return msg

    @staticmethod
    def _simplify_content(message: dict) -> dict:
        """Simplify message content to reduce token usage.

        Removes excessive whitespace, punctuation, and normalizes text
        while preserving core meaning for context storage.

        Args:
            message: Original message dict with 'content' field

        Returns:
            Message dict with simplified content
        """
        msg = message.copy()
        content = msg.get("content", "")

        if not content:
            return msg

        content = content.replace("\n", " ").replace("\r", " ").replace("\t", " ")

        chinese_punct = "，。！？；：""''""''【】《》〈〉（）—…·"
        ambiguous = "×÷·‐‑‒–—―‖′″‴‵‶‷‹›«»‚„‟†‡•‣⁃⁌⁍⁎⁏⁐⁑⁒⁓⁔⁕⁖⁗⁘⁙⁚⁛⁜⁝⁞"
        keep = "_@#$%"
        all_punct = string.punctuation + chinese_punct + ambiguous
        all_punct = "".join(c for c in all_punct if c not in keep)

        content = re.sub(f"[{re.escape(all_punct)}]", " ", content)
        content = re.sub(r"\s+", " ", content).strip()

        msg["content"] = content
        return msg
